language: java
sudo: false

cache:
  directories:
  - "$HOME/.m2"
services:
  - xvfb

notifications:
  email:
  - adsul.priya@gmail.com
before_script:
  - "export DISPLAY=:99.0"

jobs:
  include:
  # 1.1 Semver check
  - stage: test
    jdk: openjdk8
    script: mvn verify -Pcheck-semantic-version -DskipTests=true
    env: CHECK_SEMANTIC_VERSION=true

  # 1.2 Check JDK 8 and mvn
  - stage: test
    jdk: openjdk8
    script: mvn clean verify
    after_success:
      - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report

  # 1.3 Run test
  - jdk: openjdk8
    env: JAVADOC=true
    script:
    -mvn test -Dcucumber.options="--tags @Test2_FileTest1"

branches:
  only:
  - master